name: Deploy to Server

on:
  push:
    branches:
      - none

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 83.151.132.141
          username: user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/user/Hovedforl-b1-velser
            bash deploy.sh
